### ISSUE TITLE
Using date sketchy?

### ISSUE THREAD

**Issue by coolyoshi** [jat023/CS304_DB#1]
Seems to be deprecated

**Comment by rtqichen** [comment]
I think the SQL DATE is mapped to java.sql.Timestamp. I haven't actually tested this and hopefully we can figure it out once the initializedatabase code is done. (ie. we can insert a Timestamp value as a SQL DATE data type.)

**Comment by rtqichen** [comment]
Nevermind, I think we've figured it out.

**Comment by coolyoshi** [comment]
kk
